name: Add domain from config when creating issue

on:
  workflow_call:
    inputs:
      project_id:
        description: 'GitHub Project ID (optional, overrides config.json)'
        required: false
        type: string
      domain:
        description: 'Domain value (optional, overrides config.json)'
        required: false
        type: string
      date_field:
        description: 'Date field name'
        required: false
        type: string
        default: 'Date'

permissions:
  issues: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_PROJECT_TOKEN }}
  PROJECT_ID: ${{ inputs.project_id }}
  DOMAIN: ${{ inputs.domain }}
  DATE_FIELD: ${{ inputs.date_field || 'Date' }}

jobs:
  issue-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Checkout automation repository
        uses: actions/checkout@v4
        with:
          repository: leosole/github-projects-automation
          token: ${{ secrets.GH_PROJECT_TOKEN }}
          path: automation

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: automation/node_modules
          key: ${{ runner.os }}-node-20-${{ hashFiles('automation/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-20-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: automation

      
      - name: Read config
        id: config
        run: node automation/.github/scripts/read-config.js
        env:
          PROJECT_ID: ${{ inputs.project_id }}
          DOMAIN: ${{ inputs.domain }}

      - name: Add issue to project
        id: add_to_project
        run: node automation/.github/scripts/add-to-project.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          CONTENT_ID: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
          PROJECT_ID: ${{ steps.config.outputs.project_id }}

      - name: Update Domain field in project
        run: node automation/.github/scripts/add-domain.js
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          ITEM_ID: ${{ steps.add_to_project.outputs.itemId }}
          PROJECT_ID: ${{ steps.config.outputs.project_id }}
          DOMAIN: ${{ steps.config.outputs.domain }}

      - name: Set current date in Date field
        run: node automation/.github/scripts/set-date.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: ${{ steps.config.outputs.project_id }}
          FIELD_NAME: ${{ env.DATE_FIELD }}